#!/usr/bin/env bash
# scripts/poc/keycloak/setup-oidc-kubectl.sh
# Terminal access for OIDC tenants: installs kubelogin (kubectl oidc-login)
# and writes ~/.karyon/oidc.kubeconfig whose server is capsule-proxy and whose
# user is the Keycloak OIDC exec plugin (tenant-ui-oidc quick task).
#
# Flow at `kubectl get ...` time: kubelogin opens the browser (WSL mirrored
# networking → Windows browser; redirect http://localhost:8000) → Keycloak
# login (PKCE, client `kubectl`) → id_token → bearer to capsule-proxy
# https://127.0.0.1:30443 → proxy TokenReviews it against the apiserver
# (OIDC-validated) → Capsule scopes everything to the user's groups.
# Idempotent: overwrites the kubeconfig; skips the binary if present.
set -euo pipefail

readonly SPOKE_CTX="k3d-spoke-capsule"
readonly PKI="${HOME}/.karyon/oidc-pki"
readonly ISSUER="https://localhost:31443/realms/karyon"
readonly KUBELOGIN_VERSION="v1.36.2"
readonly OUT="${HOME}/.karyon/oidc.kubeconfig"
readonly BIN_DIR="${HOME}/.local/bin"

C_GREEN=$'\033[0;32m'; C_RED=$'\033[0;31m'; C_DIM=$'\033[2m'; C_RESET=$'\033[0m'
pass() { printf '%s  ok%s %s\n' "${C_GREEN}" "${C_RESET}" "$*" >&2; }
fail() { printf '%s  xx%s %s\n' "${C_RED}" "${C_RESET}" "$*" >&2; }
info() { printf '%s  ..%s %s\n' "${C_DIM}" "${C_RESET}" "$*" >&2; }

for cmd in kubectl curl unzip base64; do
  command -v "${cmd}" >/dev/null 2>&1 || { fail "required command missing: ${cmd}"; exit 1; }
done
[[ -f "${PKI}/ca.crt" ]] || { fail "OIDC CA missing — run create-tls.sh first"; exit 1; }

# ---------- kubelogin (pinned) ----------
if command -v kubectl-oidc_login >/dev/null 2>&1; then
  pass "already done, skipping: kubectl-oidc_login on PATH ($(kubectl-oidc_login --version 2>/dev/null | head -1 || echo unknown))"
else
  info "installing kubelogin ${KUBELOGIN_VERSION} to ${BIN_DIR}"
  tmp="$(mktemp -d)"
  curl -fsSL -o "${tmp}/kubelogin.zip" \
    "https://github.com/int128/kubelogin/releases/download/${KUBELOGIN_VERSION}/kubelogin_linux_amd64.zip"
  unzip -q "${tmp}/kubelogin.zip" -d "${tmp}"
  mkdir -p "${BIN_DIR}"
  install -m 0755 "${tmp}/kubelogin" "${BIN_DIR}/kubectl-oidc_login"
  rm -rf "${tmp}"
  case ":${PATH}:" in *":${BIN_DIR}:"*) : ;; *) info "NOTE: add ${BIN_DIR} to PATH" ;; esac
  pass "installed ${BIN_DIR}/kubectl-oidc_login (${KUBELOGIN_VERSION})"
fi

# ---------- capsule-proxy CA (Pitfall 10-P1: tls.crt IS the CA root) ----------
proxy_ca=$(kubectl --context "${SPOKE_CTX}" -n capsule-system get secret capsule-tls \
  -o jsonpath='{.data.tls\.crt}')
[[ -n "${proxy_ca}" ]] || { fail "capsule-tls secret unreadable"; exit 1; }
pass "capsule-proxy CA extracted"

# ---------- kubeconfig ----------
umask 077
mkdir -p "$(dirname "${OUT}")"
cat > "${OUT}" <<EOF
# Generated by scripts/poc/keycloak/setup-oidc-kubectl.sh — OIDC tenant access
# via capsule-proxy. Contains NO credentials (tokens come from the kubelogin
# browser flow at call time). Safe to regenerate anytime.
apiVersion: v1
kind: Config
clusters:
- name: karyon-capsule-proxy
  cluster:
    server: https://127.0.0.1:30443
    certificate-authority-data: ${proxy_ca}
users:
- name: oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      interactiveMode: IfAvailable
      provideClusterInfo: false
      command: kubectl
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=${ISSUER}
      - --oidc-client-id=kubectl
      - --oidc-use-pkce
      - --oidc-extra-scope=profile
      - --certificate-authority=${PKI}/ca.crt
contexts:
- name: karyon-oidc
  context:
    cluster: karyon-capsule-proxy
    user: oidc
current-context: karyon-oidc
EOF
pass "wrote ${OUT} (0600)"

printf '\n%sOIDC kubectl ready.%s Try:\n' "${C_GREEN}" "${C_RESET}" >&2
printf '%s  kubectl --kubeconfig %s auth whoami%s\n' "${C_DIM}" "${OUT}" "${C_RESET}" >&2
printf '%s  kubectl --kubeconfig %s get namespaces   # tenant-scoped via capsule-proxy%s\n' "${C_DIM}" "${OUT}" "${C_RESET}" >&2
printf '%s  (auth retries: rm -rf ~/.kube/cache/oidc-login)%s\n' "${C_DIM}" "${C_RESET}" >&2
